name: AZL Conduit
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run AZL Conduit
        run: python main.py
      - name: Verify Return Code
        run: exit $? # Fails CI if Return Code: 1
